/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.org.linlinjava.litemall.db.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.linlinjava.litemall.db.domain.LitemallRegionExample;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class LitemallRegionExample_SSTest extends LitemallRegionExample_SSTest_scaffolding {
// allCoveredLines:[37, 38, 39, 48, 49, 58, 68, 69, 78, 88, 98, 99, 108, 109, 110, 120, 121, 131, 132, 133, 134, 135, 138, 139, 149, 150, 151, 153, 163, 164, 174, 175, 176, 177, 186, 187, 197, 198, 200, 210, 211, 213, 215, 228, 229, 230, 928, 929, 930, 939, 963, 964, 966, 976, 977, 979, 981]

  @Test(timeout = 4000)
  public void test_clear_00()  throws Throwable  {
      //caseID:86a0b8158462b643df1494a75e079d43
      //CoveredLines: [37, 38, 39, 174, 175, 176, 177]
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: clear
      litemallRegionExample0.clear();
      
      //Test Result Assert
      assertFalse(litemallRegionExample0.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_example_01()  throws Throwable  {
      //caseID:8959c9e42c6dd61d3644ab378faa6a73
      //CoveredLines: [37, 38, 39, 149, 150, 151, 153, 163, 164, 186, 187, 228, 229, 230, 928, 929, 930, 939]
      //Assert: assertFalse(method_result.isDistinct());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = LitemallRegionExample.newAndCreateCriteria();
      
      //Call method: example
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample_Criteria0.example();
      
      //Test Result Assert
      assertFalse(litemallRegionExample1.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_getOrderByClause_02()  throws Throwable  {
      //caseID:98f6016bee8e166d3850145f8a59fa4c
      //CoveredLines: [37, 38, 39, 58]
      //Assert: assertNull(method_result);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: getOrderByClause
      String string0 = litemallRegionExample0.getOrderByClause();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getOredCriteria_03()  throws Throwable  {
      //caseID:a78916d0021e02ce7f71ef1e77afa18b
      //CoveredLines: [37, 38, 39, 88]
      //Assert: assertTrue(method_result.isEmpty());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: getOredCriteria
      List<LitemallRegionExample.Criteria> list0 = litemallRegionExample0.getOredCriteria();
      
      //Test Result Assert
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_getSecondValue_04()  throws Throwable  {
      //caseID:46c1daad990ad222186ddc3fb2c7d5fc
      //CoveredLines: [37, 38, 39, 149, 150, 153, 163, 164, 228, 229, 230, 928, 929, 930, 976, 977, 981]
      //Assert: assertSame(method_result, litemallRegionExample_Criteria1);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      LinkedList<LitemallRegionExample.Criteria> linkedList0 = new LinkedList<LitemallRegionExample.Criteria>();
      //mock litemallRegionExample_Criteria0
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = mock(LitemallRegionExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      linkedList0.add(litemallRegionExample_Criteria0);
      PrivateAccess.setVariable((Class<?>) LitemallRegionExample.class, litemallRegionExample0, "oredCriteria", (Object) linkedList0);
      LitemallRegionExample.Criteria litemallRegionExample_Criteria1 = litemallRegionExample0.createCriteria();
      //mock litemallRegionExample_ICriteriaWhen0
      LitemallRegionExample.ICriteriaWhen litemallRegionExample_ICriteriaWhen0 = mock(LitemallRegionExample.ICriteriaWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      LitemallRegionExample.Criteria litemallRegionExample_Criteria2 = litemallRegionExample_Criteria1.when(true, litemallRegionExample_ICriteriaWhen0, litemallRegionExample_ICriteriaWhen0);
      //mock litemallRegionExample_Criterion0
      LitemallRegionExample.Criterion litemallRegionExample_Criterion0 = mock(LitemallRegionExample.Criterion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(litemallRegionExample_Criteria2).when(litemallRegionExample_Criterion0).getSecondValue();
      
      //Call method: getSecondValue
      Object object0 = litemallRegionExample_Criterion0.getSecondValue();
      
      //Test Result Assert
      assertSame(object0, litemallRegionExample_Criteria1);
  }

  @Test(timeout = 4000)
  public void test_getSecondValue_05()  throws Throwable  {
      //caseID:e0e47908d30213b9eba852f25b85cd78
      //CoveredLines: [37, 38, 39, 149, 150, 153, 163, 164, 228, 229, 230, 928, 929, 930, 976, 979, 981]
      //Assert: assertSame(litemallRegionExample_Criteria2, method_result);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      LinkedList<LitemallRegionExample.Criteria> linkedList0 = new LinkedList<LitemallRegionExample.Criteria>();
      //mock litemallRegionExample_Criteria0
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = mock(LitemallRegionExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      linkedList0.add(litemallRegionExample_Criteria0);
      PrivateAccess.setVariable((Class<?>) LitemallRegionExample.class, litemallRegionExample0, "oredCriteria", (Object) linkedList0);
      LitemallRegionExample.Criteria litemallRegionExample_Criteria1 = litemallRegionExample0.createCriteria();
      //mock litemallRegionExample_ICriteriaWhen0
      LitemallRegionExample.ICriteriaWhen litemallRegionExample_ICriteriaWhen0 = mock(LitemallRegionExample.ICriteriaWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      LitemallRegionExample.Criteria litemallRegionExample_Criteria2 = litemallRegionExample_Criteria1.when(false, litemallRegionExample_ICriteriaWhen0, litemallRegionExample_ICriteriaWhen0);
      //mock litemallRegionExample_Criterion0
      LitemallRegionExample.Criterion litemallRegionExample_Criterion0 = mock(LitemallRegionExample.Criterion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(litemallRegionExample_Criteria2).when(litemallRegionExample_Criterion0).getSecondValue();
      
      //Call method: getSecondValue
      Object object0 = litemallRegionExample_Criterion0.getSecondValue();
      
      //Test Result Assert
      assertSame(litemallRegionExample_Criteria2, object0);
  }

  @Test(timeout = 4000)
  public void test_isDistinct_06()  throws Throwable  {
      //caseID:f72e481d11b441908faa2f9bb8876ffa
      //CoveredLines: [37, 38, 39, 78]
      //Assert: assertFalse(method_result);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: isDistinct
      boolean boolean0 = litemallRegionExample0.isDistinct();
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_or_07()  throws Throwable  {
      //caseID:fd45201be34c5c378944201ed074358b
      //CoveredLines: [37, 38, 39, 98, 99]
      //Input_0_LitemallRegionExample$Criteria: {}
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      //mock litemallRegionExample_Criteria0
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = mock(LitemallRegionExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: or
      litemallRegionExample0.or(litemallRegionExample_Criteria0);
      
      //Test Result Assert
      assertFalse(litemallRegionExample0.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_orderBy_08()  throws Throwable  {
      //caseID:30d6ca99da68ca5483fd858d82a6c0cf
      //CoveredLines: [37, 38, 39, 48, 49, 120, 121]
      //Input_0_String: "code = "
      //Assert: assertEquals("code = ", litemallRegionExample0.getOrderByClause());
      //Assert: assertEquals("code = ", method_result.getOrderByClause());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: orderBy
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.orderBy("code = ");
      
      //Test Result Assert
      assertEquals("code = ", litemallRegionExample0.getOrderByClause());
      
      //Test Result Assert
      assertEquals("code = ", litemallRegionExample1.getOrderByClause());
  }

  @Test(timeout = 4000)
  public void test_orderBy_09()  throws Throwable  {
      //caseID:d04835c99e286260c77c7adb4012aba3
      //CoveredLines: [37, 38, 39, 48, 49, 131, 132, 133, 134, 135, 138, 139]
      //Input_0_String[]: stringArray0
      //Assert: assertEquals("null , null , null , null , null , null , null , null , null , null", method_result.getOrderByClause());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      String[] stringArray0 = new String[10];
      
      //Call method: orderBy
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.orderBy(stringArray0);
      
      //Test Result Assert
      assertEquals("null , null , null , null , null , null , null , null , null , null", litemallRegionExample1.getOrderByClause());
  }

  @Test(timeout = 4000)
  public void test_setDistinct_10()  throws Throwable  {
      //caseID:ffbf941fa61d011814809e9b99e7247c
      //CoveredLines: [37, 38, 39, 68, 69]
      //Input_0_boolean: false
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      
      //Call method: setDistinct
      litemallRegionExample0.setDistinct(false);
      
      //Test Result Assert
      assertFalse(litemallRegionExample0.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_when_11()  throws Throwable  {
      //caseID:bb7d9fc494eef93dea09b42447dd9a17
      //CoveredLines: [37, 38, 39, 197, 200]
      //Input_0_boolean: false
      //Input_1_LitemallRegionExample$IExampleWhen: {}
      //Assert: assertFalse(method_result.isDistinct());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      //mock litemallRegionExample_IExampleWhen0
      LitemallRegionExample.IExampleWhen litemallRegionExample_IExampleWhen0 = mock(LitemallRegionExample.IExampleWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.when(false, litemallRegionExample_IExampleWhen0);
      
      //Test Result Assert
      assertFalse(litemallRegionExample1.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_when_12()  throws Throwable  {
      //caseID:01fd6a4726ce3aa76c666be7bc18b3e0
      //CoveredLines: [37, 38, 39, 210, 211, 215]
      //Input_0_boolean: true
      //Input_1_LitemallRegionExample$IExampleWhen: {}
      //Input_2_LitemallRegionExample$IExampleWhen: {}
      //Assert: assertNull(method_result.getOrderByClause());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      //mock litemallRegionExample_IExampleWhen0
      LitemallRegionExample.IExampleWhen litemallRegionExample_IExampleWhen0 = mock(LitemallRegionExample.IExampleWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.when(true, litemallRegionExample_IExampleWhen0, litemallRegionExample_IExampleWhen0);
      
      //Test Result Assert
      assertNull(litemallRegionExample1.getOrderByClause());
  }

  @Test(timeout = 4000)
  public void test_when_13()  throws Throwable  {
      //caseID:e32d330210c5c92077fc8f9ac028e50a
      //CoveredLines: [37, 38, 39, 210, 213, 215]
      //Input_0_boolean: false
      //Input_1_LitemallRegionExample$IExampleWhen: {}
      //Input_2_LitemallRegionExample$IExampleWhen: {}
      //Assert: assertFalse(method_result.isDistinct());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      //mock litemallRegionExample_IExampleWhen0
      LitemallRegionExample.IExampleWhen litemallRegionExample_IExampleWhen0 = mock(LitemallRegionExample.IExampleWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.when(false, litemallRegionExample_IExampleWhen0, litemallRegionExample_IExampleWhen0);
      
      //Test Result Assert
      assertFalse(litemallRegionExample1.isDistinct());
  }

  @Test(timeout = 4000)
  public void test_when_14()  throws Throwable  {
      //caseID:57b98495fd2b3e740b2893b427149a9c
      //CoveredLines: [37, 38, 39, 197, 198, 200]
      //Input_0_boolean: true
      //Input_1_LitemallRegionExample$IExampleWhen: {}
      //Assert: assertNull(method_result.getOrderByClause());
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      //mock litemallRegionExample_IExampleWhen0
      LitemallRegionExample.IExampleWhen litemallRegionExample_IExampleWhen0 = mock(LitemallRegionExample.IExampleWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample litemallRegionExample1 = litemallRegionExample0.when(true, litemallRegionExample_IExampleWhen0);
      
      //Test Result Assert
      assertNull(litemallRegionExample1.getOrderByClause());
  }

  @Test(timeout = 4000)
  public void test_when_15()  throws Throwable  {
      //caseID:f8ae18b962d6f12cebbafe4c7b33b636
      //CoveredLines: [37, 38, 39, 108, 109, 110, 163, 164, 228, 229, 230, 928, 929, 930, 963, 966]
      //Input_0_boolean: false
      //Input_1_LitemallRegionExample$ICriteriaWhen: {}
      //Assert: assertSame(litemallRegionExample_Criteria0, method_result);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = litemallRegionExample0.or();
      //mock litemallRegionExample_ICriteriaWhen0
      LitemallRegionExample.ICriteriaWhen litemallRegionExample_ICriteriaWhen0 = mock(LitemallRegionExample.ICriteriaWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample.Criteria litemallRegionExample_Criteria1 = litemallRegionExample_Criteria0.when(false, litemallRegionExample_ICriteriaWhen0);
      
      //Test Result Assert
      assertSame(litemallRegionExample_Criteria0, litemallRegionExample_Criteria1);
  }

  @Test(timeout = 4000)
  public void test_when_16()  throws Throwable  {
      //caseID:1471202d632149dd53c58fd9c483c07a
      //CoveredLines: [37, 38, 39, 108, 109, 110, 163, 164, 228, 229, 230, 928, 929, 930, 963, 964, 966]
      //Input_0_boolean: true
      //Input_1_LitemallRegionExample$ICriteriaWhen: {}
      //Assert: assertSame(litemallRegionExample_Criteria0, method_result);
      
      LitemallRegionExample litemallRegionExample0 = new LitemallRegionExample();
      LitemallRegionExample.Criteria litemallRegionExample_Criteria0 = litemallRegionExample0.or();
      //mock litemallRegionExample_ICriteriaWhen0
      LitemallRegionExample.ICriteriaWhen litemallRegionExample_ICriteriaWhen0 = mock(LitemallRegionExample.ICriteriaWhen.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: when
      LitemallRegionExample.Criteria litemallRegionExample_Criteria1 = litemallRegionExample_Criteria0.when(true, litemallRegionExample_ICriteriaWhen0);
      
      //Test Result Assert
      assertSame(litemallRegionExample_Criteria0, litemallRegionExample_Criteria1);
  }
}
